### ISSUE TITLE
cess config set 这步不填IP,结束配置内容后又提示是什么操作

### ISSUE THREAD

**Issue by huayanby** [CESSProject/cess-bucket#174]
cess config set 时，没让输入IP啊，配置完成时提示Set configurations successfully，接着就提示Start generate configurations and docker compose file
debug: Loading config file: config.yaml
error: failed to load config: '"node.externalIp" is not allowed to be empty'
Trace: [Error [ValidationError]: "node.externalIp" is not allowed to be empty] {
这里提示没有IP,这不是前后矛盾吗?

**Comment by zoushui** [comment]
之前跑过前面版本测试的机器，先执行完 cess pullimg，再执行 cess config set 这一步
