### ISSUE TITLE
3 nodes of 4 is not getting storage verified

### ISSUE THREAD

**Issue by Kekksik** [CESSProject/cess-bucket#186]
three nodes of four does not get storage verified for 4 days already. There is no errors in logs
staking addresses are
cXhxtHBSk5yicDbeoGFKNdgptidGeQgjMe4Am2XJjdmfup8E7
cXiP9A1xRuGkU8dnr3qBWp5T7BqJcbAfzVpqGm7NYnHpAQL1q
cXgencksSUsosSUYf6iQwZgKyQPVYSjxRS2b36mX7fDZmooFv

I have 4th node which has similar technical characteristics but it gets storage verified 
staking address is
cXgqNFFxw15Q6uvFwbuCZNkoFEotnhwmiegvjg7Zm7xqyocBy

![image](https://github.com/CESSProject/cess-bucket/assets/113889229/35868503-ed84-4cf2-b90a-503d81192d0a)
please help

**Comment by AstaFrode** [comment]
@Kekksik Please check whether your storage nodes are still running normally, or restart them.

**Comment by Kekksik** [comment]
ok, I'll do

**Comment by Kekksik** [comment]
there was no errors. I reloaded anyway. 
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/57a768ff-22d7-4425-9517-3cf1c2c2ab8e)
substats show the same situation
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/7baa7fec-0e68-47ee-a402-b212c8902796)

**Comment by AstaFrode** [comment]
@Kekksik Take a look: /workspace/cXiP9A1xRuGkU8dnr3qBWp5T7BqJcbAfzVpqGm7NYnHpAQL1q/bucket/log/space.log
`/workspace` is the directory you configured yourself.

**Comment by Kekksik** [comment]
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/0a74a4be-2bde-4f9e-a2e4-85d87e0bb752)
guess I need to delete last node workspace?

**Comment by AstaFrode** [comment]
If your disk space is less than 32G, the space will not be verified.

**Comment by Kekksik** [comment]
I have more than 32Gb. It seems that last node workspace reserved it. I'm working in that direction now

**Comment by Kekksik** [comment]
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/5c23616f-2076-4e07-ac91-b41dd47691a0)
looks like it helped, we'll see
Thanks!

**Comment by Kekksik** [comment]
@AstaFrode heya!
now I have:
- 1 node with Init POIS error, and bucket can't start (that issue appeared after server reinstall)
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/44944eb0-c3f7-448c-959b-3f152fe6c3c3)
 - 2 nodes with enough space but without growing of validated space and mining rewards. And bucket restarts about every 30 minutes - 1 hour
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/50480ced-9cf9-4fff-b599-a84f9e6329c8)
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/3c908df2-2fbd-44a5-bcb8-df5c6bba65ac)
also updated time was very long ago
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/794a9d90-cb8c-443c-b3da-b1ef03a790ea)
do I need to do anything?

**Comment by AstaFrode** [comment]
@Kekksik 
- Check your data location, for example in /cess/cXhxt...8E7/bucket/..., you need to reconfigure the workspace to /cess before starting.
- If the space is not growing, you can check the log: /workspace/cXgenck...mooFv/bucket/log/space.log
- The problem of no reward may be: first, there is no challenge to your node, and second, there is a challenge to your node but it is not completed. At present, there is no challenge to your node.
