### ISSUE TITLE
json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

### ISSUE THREAD

**Issue by refangga1337** [CESSProject/cess-bucket#187]
Node synced but i got this : json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

![Screenshot_2023-09-22-15-48-12-45_61c78dc80ee02b53007c815fefe993e3](https://github.com/CESSProject/cess-bucket/assets/102345142/58b173e1-8a00-4da3-b0bd-0f97f4423abc)

**Comment by AstaFrode** [comment]
@refangga1337 Update cess-nodeadm to v0.4.4:
```
cess stop
cess down
wget https://github.com/CESSProject/cess-nodeadm/archive/v0.4.4.tar.gz
tar -xvf v0.4.4.tar.gz
cd cess-nodeadm-0.4.4/
./install.sh
cess profile testnet
cess config generate
cess config set
cess start
```
