### ISSUE TITLE
Validated space not increase in 3 weeks

### ISSUE THREAD

**Issue by thuyld** [CESSProject/cess-bucket#188]
I installed as a storage miner, but 3 weeks have passed, my validated space has not increased at all, even though I updated to the latest version 0.4.4.
Please check it for me and give me feedback.

![image](https://github.com/CESSProject/cess-bucket/assets/55678638/f6796025-2aa1-45a8-a045-58cc3557d421)

**Comment by AstaFrode** [comment]
@thuyld Judging from the block height, there is a problem with the chain node you configured. The current block height of the test network is 247647. You can try again by referring to the following process:
```
cess stop
cess down
wget https://github.com/CESSProject/cess-nodeadm/archive/v0.4.4.tar.gz
tar -xvf v0.4.4.tar.gz
cd cess-nodeadm-0.4.4/
./install.sh
cess profile testnet
cess config generate
cess config set
cess start
```
