### ISSUE TITLE
Connection refused errors

### ISSUE THREAD

**Issue by Kekksik** [CESSProject/cess-bucket#198]
All my nodes hve the same issue
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/619df1dc-d1a0-4dec-b8a7-6cc501852d69)

What can I do?

**Comment by Kekksik** [comment]
no, it happened again
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/fb2e4d3a-b4cb-4c38-a582-7f39be486a66)

How to fix it?

**Comment by AstaFrode** [comment]
@Kekksik You do not need to be concerned about this issue because this issue does not have a functional impact on the storage node and the issue occurs in the gateway service because the gateway server is undergoing maintenance.
