### ISSUE TITLE
How to revive punished to 0 node?

### ISSUE THREAD

**Issue by Kekksik** [CESSProject/cess-bucket#203]
one of my nodes got punished to 0 and node went offline. I do faucet and have tokens on my wallet, but can't revive it. What can I do with it? 
cess bucket increase doesn't work
bucket can't start. I tried everything I know. I need help
![image](https://github.com/CESSProject/cess-bucket/assets/113889229/99539aeb-18f5-41c6-82ab-dcbe96cfa806)

![image](https://github.com/CESSProject/cess-bucket/assets/113889229/22dc8bbf-2eee-41df-8349-e6ba51e6ab8c)

**Comment by AstaFrode** [comment]
@Kekksik If the storage node status changes to "offline", it means that the node did not complete the challenge and was punished. The offline node in the v0.7.4 version has no effect. You can run with a new account.
