### ISSUE TITLE
rpc issues

### ISSUE THREAD

**Issue by khalography** [CESSProject/cess-bucket#229]
i have been having rpc connection issues for the past three days even after doing a restart on two occasions. 
![Uploading Screenshot 2024-01-24 102029.png…]()

**Comment by AstaFrode** [comment]
@khalography I can't see your picture，Since the number of nodes is large, you can improve by switching different rpc nodes:
wss://testnet-rpc0.cess.cloud/ws/
wss://testnet-rpc1.cess.cloud/ws/
wss://testnet-rpc2.cess.cloud/ws/
