### ISSUE TITLE
Docker logs not running

### ISSUE THREAD

**Issue by moontrader2009** [CESSProject/cess-bucket#238]
Hello. I would like to raise an issue when running docker logs. When I enter command, it shows nothing. I don't know if my storage node has not been set-up good but I am quite sure I did the right thing. My node is running because I was able to validate space. I cannot just check docker logs. 
![cess](https://github.com/CESSProject/cess-bucket/assets/112131390/cb5e8b02-7195-4609-845c-db16213a1434)

**Comment by AstaFrode** [comment]
@moontrader2009 From the docker logs, your storage node situation is normal, if you want to see more logs, please go to your configured directory, specifically in: <workspace>/<signature account address>/bucket/log/
