### ISSUE TITLE
配置挖矿操作问题

### ISSUE THREAD

**Issue by cainiaobibi** [CESSProject/cess-bucket#24]
1.注册矿工时meat mask钱包会合约交互失败导致无法注册矿工
2.挖矿miner配置时将钱包中的私钥已经写入priv文件却使用geth account import  ./priv生成keystore文件时出现找不到私钥的错误
![屏幕截图 2022-04-20 040658](https://user-images.githubusercontent.com/85666569/164086969-06d7f0db-0252-4a13-88a2-35ca7d21c2fb.png)

**Comment by heyworld88** [comment]
cc @swowk Hi, I'd like to response you issue, but my chinese is poor. Ted，can you help me to response this issue?

**Comment by ted-tech** [comment]
@cainiaobibi 你这个问题是的原因是没找到priv这个文件，你可以试试“geth account import priv”
