### ISSUE TITLE
failed: no Sminer.Registered event found

### ISSUE THREAD

**Issue by wowvwow** [CESSProject/cess-bucket#241]
Node mode: storage
Profile: testnet
nodeadm version: v0.5.3
Docker images:
  config-gen: config-gen 1.5.0 0463ecad5706
  chain: cess-node 0.7.6-d2220c01057 a1d3bedfa350
  bucket: bucket v0.7.9 98ab5c0af899

++ 2024-02-06 17:16:22 Listening on port: 6000
++ 2024-02-06 17:16:22 RPC addresses: [ws://192.168.50.30:59944]
++ 2024-02-06 17:16:22 Bootnodes: [_dnsaddr.boot-bucket-testnet.cess.cloud]
++ 2024-02-06 17:16:24 Local peer id: 12D3KooWQRvE438TzxRd6yu9aPsYFpW4veoaY4QCgwgK257My4eu
++ 2024-02-06 17:16:24 Chain network: cess-testnet
++ 2024-02-06 17:16:24 P2P network: cess-testnet
++ 2024-02-06 17:16:24 Number of cpu cores used: 4
++ 2024-02-06 17:16:24 RPC address used: ws://192.168.50.30:59944
OK 2024-02-06 17:16:24 Synchronization main chain completed: 90058
++ 2024-02-06 17:16:24 Connected to 12D3KooWS8a18xoBzwkmUsgGBctNo6QCr6XCpUDR946mTBBUTe83 successfully
++ 2024-02-06 17:16:24 Connected to 12D3KooWDWeiiqbpNGAqA5QbDTdKgTtwX8LCShWkTpcyxpRf2jA9 successfully
++ 2024-02-06 17:16:24 Connected to 12D3KooWNcTWWuUWKhjTVDF1xZ38yCoHXoF4aDjnbjsNpeVwj33U successfully
XX 2024-02-06 17:16:30 [0x1ff2f18fc3a732febf6b4de77a389800fd7caba7b357a2ebd4bee18f2874ce1a] failed: no Sminer.Registered event found

**Comment by AstaFrode** [comment]
@wowvwow 
1. First of all, make sure that the balance in your signature account is greater than 1 TCESS.
2. If your Signature Account is the same as your Staking Account, you need to make sure that the balance in your Signature Account is sufficient to cover the deposit, which is calculated based on 4000 TCESS per TiB.
3. If your Signature Account and Staking Account are different, you need to have someone with the Staking Account to make the pledge for you.
