### ISSUE TITLE
About RPC errors

### ISSUE THREAD

**Issue by unkomoreta11** [CESSProject/cess-bucket#242]
When I run "docker logs bucket",

rpc err: [ws://127.0.0.1:9944] [st] [Sminer.Expenders] CreateStorageKey: module Sminer not found in metadata

![2024-02-11 143351](https://github.com/CESSProject/cess-bucket/assets/85406052/d4b58a54-d287-4646-b52a-4f44129788d5)

I get the above error.

I added "wss://testnet-rpc2.cess.cloud/ws/" to config.yaml but it does not improve.

Is there any way to deal with this?

**Comment by AstaFrode** [comment]
@unkomoreta11 Your old chain from the last version seems to still be running, and your block height is already higher than the latest version of the chain, so you'll have to stop the old chain before running it again.
