### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by tamckd1** [CESSProject/cess-bucket#245]
![image](https://github.com/CESSProject/cess-bucket/assets/88770649/60db6a8a-a457-424b-8564-aa43f41a4772)
![image](https://github.com/CESSProject/cess-bucket/assets/88770649/a5205e2a-2051-4426-a67c-fb7c454fe294)

2024-02-24 03:27:03 💤 Idle (105 peers), best: #339358 (0x7de7…06e0), finalized #339356 (0x60c6…a51a), ⬇ 1.1MiB/s ⬆ 750.8kiB/s

plz support me to solve this error. Thank you so much

**Comment by AstaFrode** [comment]
@tamckd1 If the connection fails, it will be reconnected. Don’t worry about this problem.
