### ISSUE TITLE
Account hacked

### ISSUE THREAD

**Issue by zzagi73** [CESSProject/cess-bucket#246]
I bought 10 cess with 0.5eth
My wallet was compromised and the hacker attached a sweeper bot. Is there a way to change my wallet? The address I contributed was 0x43bEAAf55b402A7b59b8d2696eC040Fd09f6c001

**Comment by ytqaljn** [comment]
The `cess-node` program should only occupy 4 of your ports. If you start it through the nodeam, it will include other programs.
