### ISSUE TITLE
websocket: bad handshake 

### ISSUE THREAD

**Issue by samboluy** [CESSProject/cess-bucket#247]
Hi Team, may be there is a problem with RPC or port somewhere: 
websocket: bad handshake (HTTP status 429 Too Many Requests)

**Comment by AstaFrode** [comment]
@samboluy You can wait for it to automatically switch to other RPC nodes, or run your own RPC node, using the following two methods:
https://docs.cess.cloud/core/storage-miner/multi-buckets#run-rpc-nodes-through-the-cess-nodeadm-program
https://docs.cess.cloud/core/storage-miner/multi-buckets#run-the-cess-node-program-directly
