### ISSUE TITLE
Broken link to browser

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess-bucket#40]
Browser access :https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcess.today%2Frpc2-hacknet%2Fws%2F#/accounts in the README does not work.

I think the endpoint should be replaced by: wss://testnet-rpc.cess.cloud/ws/

**Comment by ted-tech** [comment]
We apologize for the inconvenience.
We are about to release the v0.4 version, and this link will be updated synchronously at that time.

**Comment by ted-tech** [comment]
@NachoPal Hello, you can now access our blockchain explorer: https://testnet-rpc.cess.cloud/explorer/#/explorer

**Comment by AstaFrode** [comment]
https://testnet-rpc.cess.cloud/explorer/#/explorer
