### ISSUE TITLE
mining reward question

### ISSUE THREAD

**Issue by wolfeagle6611** [CESSProject/cess-bucket#5]
when i  cancel the cess mining system, the tips show i should keep the mining machine running and get the staking back on 30 days. but the question is my mining machine was shut down already, can i get my staking and mining reward back ?

**Comment by ted-tech** [comment]
When mining is cancelled, it will enter a 30-day cooling-off period. During the cooling-off period, you need to keep your normal online connection, otherwise you will be punished. The deposit can be redeemed when the cooling-off period expires.

**Comment by Aranck** [comment]
wow nice issue and answer, I knew that point now.
