### ISSUE TITLE
miner space requirement

### ISSUE THREAD

**Issue by Aranck** [CESSProject/cess-bucket#7]
Is there have any requirement for miner space? If so, what is it?

**Comment by ted-tech** [comment]
There is no special requirement for the space of the mining machine, and ordinary hard disks can be used for mining.

**Comment by Aranck** [comment]
clear, thank you. by the way, is it the miner space bigger, the more reward I can get?

**Comment by ted-tech** [comment]
Yes, the bigger the space, the more rewards.
